env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:nuxt/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {}
